"""new orm scheme

Revision ID: c1a9bcac097a
Revises: 4d7c58e62be1
Create Date: 2024-01-18 21:20:25.459326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a9bcac097a'
down_revision: Union[str, None] = '4d7c58e62be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refreshTokenUser')
    op.drop_table('refreshToken')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshToken',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"refreshToken_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rewoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='refreshToken_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('refreshTokenUser',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshToken.id'], name='refreshTokenUser_refresh_token_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='refreshTokenUser_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'refresh_token_id', name='refreshTokenUser_pkey')
    )
    # ### end Alembic commands ###
