"""fix token

Revision ID: 19cfc323707a
Revises: c1a9bcac097a
Create Date: 2024-01-18 22:41:06.197462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cfc323707a'
down_revision: Union[str, None] = 'c1a9bcac097a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshToken',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('rewoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('refreshTokenUser',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_jti', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_jti'], ['refreshToken.jti'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'refresh_token_jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refreshTokenUser')
    op.drop_table('refreshToken')
    # ### end Alembic commands ###
