"""add Refresh token

Revision ID: 0b9c5abacfb2
Revises: 0ce0eda181f1
Create Date: 2024-01-18 03:07:16.083189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9c5abacfb2'
down_revision: Union[str, None] = '0ce0eda181f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshToken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('rewoked', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refreshTokenUser',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshToken.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'refresh_token_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refreshTokenUser')
    op.drop_table('refreshToken')
    # ### end Alembic commands ###
