"""add message

Revision ID: 61a6c82af28b
Revises: 2e3f229a1dd7
Create Date: 2024-01-26 22:14:00.375203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a6c82af28b'
down_revision: Union[str, None] = '2e3f229a1dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('isEdit', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRead', sa.Boolean(), nullable=False),
    sa.Column('isAudio', sa.Boolean(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('idRoom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idRoom'], ['room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
